/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 27 13:00:42 GMT 2020
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true)
public class Mutation_ESTest extends Mutation_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Mutation mutation0 = new Mutation();
      boolean boolean0 = mutation0.isPositive(3893);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Mutation mutation0 = new Mutation();
      boolean boolean0 = mutation0.isPositive(0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Mutation mutation0 = new Mutation();
      boolean boolean0 = mutation0.isPositive(101);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Mutation mutation0 = new Mutation();
      boolean boolean0 = mutation0.isPositive((-4284));
      assertFalse(boolean0);
  }
}
